[package]
name = "single_buffer_channel"
description = "Multi-producer, single-consumer single value communication primitives."
version = "0.1.0"
authors = ["Amelia10007 <nat.horn.mk0426@gmail.com>"]
edition = "2018"
licence = "Apache-2.0"
